#!/bin/sh
sh_files=$(git diff --cached --name-only | grep '\.sh$')
echo 'sh_files:'
echo $sh_files
rs_files=$(git diff --cached --name-only | grep '\.rs$')
echo 'rs_files:'
echo $rs_files

if rs_files; then
	sh scripts.sh lint
fi
