#!/bin/sh
sh_files=$(git diff --cached --name-only | grep '\.sh$')
echo 'sh_files:'
echo $sh_files
rs_files=$(git diff --cached --name-only | grep '\.rs$')
echo 'rs_files:'
echo $rs_files

if rs_files; then
	echo "Файлы с расширением .rs найдены в последнем коммите."
	sh scripts.sh lint
else
	echo "Файлы с расширением .rs НЕ найдены в последнем коммите."
fi
